### ISSUE TITLE
to data frame

### ISSUE THREAD

**Issue by ggrothendieck** [gdemin/comprehenr#2]
This gives the desired result but I wondered if it was the best way?  I was looking for something like to_data.frame but the closest I found was to_list followed by rbind as shown.

```
f <- function(x, y) x + y^2
v <- 2:3
L <- to_list(for(a in v) for(b in v)  data.frame(a, b, result = f(a, b)))
do.call("rbind", L)
```

Update: fixed code

**Comment by gdemin** [comment]
Something better is `rbindlist` from data.table package.
I will introduce `to_df` in the next version.

**Comment by gdemin** [comment]
'to_df' was added in version 0.6.10
